- file:
    mode: '0755'
    path: src/automation/configs
    state: directory
  name: Create configs directory
- name: Generate full config from template
  tags:
  - all
  template: src=master_template.j2 dest=../configs/{{ item.hostname }}_all.txt
  with_items: '{{ routers }}'
