all:
  children:
    routers:
      hosts:
        router1:
          ansible_connection: network_cli
          ansible_host: 192.168.100.1
          ansible_network_os: ios
          ansible_password: lab123
          ansible_user: admin
        router2:
          ansible_connection: network_cli
          ansible_host: 192.168.100.2
          ansible_network_os: ios
          ansible_password: lab123
          ansible_user: admin
        router3:
          ansible_connection: network_cli
          ansible_host: 192.168.100.3
          ansible_network_os: ios
          ansible_password: lab123
          ansible_user: admin
        router4:
          ansible_connection: network_cli
          ansible_host: 192.168.100.4
          ansible_network_os: ios
          ansible_password: lab123
          ansible_user: admin
        router5:
          ansible_connection: network_cli
          ansible_host: 192.168.100.5
          ansible_network_os: ios
          ansible_password: lab123
          ansible_user: admin
